
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjhculqiipzmnezvbxeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqaGN1bHFpaXB6bW5lenZieGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjI1NDQsImV4cCI6MjA1OTU5ODU0NH0.xpMxMH-0Y-ZrfBHOpKF5S6xrEfu7OMAP_pM1-52517U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
